library(knitr)
library(rvest)
library(gsubfn)
library(shiny)
library(readr)
library(tidyr)
library(dplyr)
library(tibble)
# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
