library(knitr)
library(rvest)
library(gsubfn)
library(shiny)
library(readr)
library(tidyr)
library(dplyr)
library(tibble)
library(rgdal)
library(ggplot2)
library(mosaic)
library(rgeos)
library(rworldmap)
library(maptools)
library(rgdal)
library(ggmap)
library(ggvis)
library(rgeos)
library(RColorBrewer)
library(geojsonio)
library(spdplyr)
library(rmapshaper)
library(leaflet)
library(raster)
library(viridis)
library(cowplot)
library("stringr")
# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")

